sync test chart & scripts
celo-org/infrastructure pull request #1
Opened 2020-09-25 16:49 UTC by hbandura

2020-09-25 19:48 UTC, jcortejoso requested changes
Nice PR. I am leaving some comments based most on https://www.shellcheck.net/.

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +if [ $LATEST -eq $LATEST 2> /dev/null ]; then
I think `2> /dev/null` is not necessary here.

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +POD=`kubectl -n $NAMESPACE get pods -o name -l app=sync-test-node -l dockertag=$TAG`
`...` is usually considered as deprecated syntax, being $(...) preferred ([SC2006](https://github.com/koalaman/shellcheck/wiki/SC2006))

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +    DIFF="$(($LATEST - $MARK))"
I would use `DIFF="$((LATEST - MARK))"` to use the same syntax as in the next line

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +fi
You can consider leaving a new line at EOF ([reason](https://thoughtbot.com/blog/no-newline-at-end-of-file))

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +    exit 1001
Allowed exit codes go from 0 to 255

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +        echo "Sync not completed. Latest block is $((-DIFF)) seconds old"
Is there any difference to `-$DIFF` syntax?

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/wait_for_sync.sh
> +while [ $SECONDS -lt $END_TIME ]; do
$SECONDS in not available in some sh shells ([SC3028](https://github.com/koalaman/shellcheck/wiki/SC3028)). You can 'force' the shebang to bash.

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/wait_for_sync.sh
> +    exit 1001
Exit code between 0 and 255

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/stop.sh
> +    exit 1001
Exit code between 0 and 255

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/start.sh
> + --name $RELEASE --set dockertag=$TAG --set geth.syncmode=$SYNCMODE
Newline at EOF

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/stop.sh
> +helm del --purge $RELEASE
Newline at EOF

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/wait_for_sync.sh
> +exit 1
Newline at EOF

2020-09-25 19:48 UTC, jcortejoso commented on helm-charts/sync-test-node/values.yaml
> +      cpu: "2000m"
Seems a bit high to the values I am used to use, but I am ok with being generous. Also consider `requests` is a soft limit, so the pod could use more resources if the node where it runs have free resources.

2020-09-25 20:37 UTC, hbandura commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +        echo "Sync not completed. Latest block is $((-DIFF)) seconds old"
If DIFF is -3, I want it to show '3' (diff is negative usually)

2020-09-25 20:37 UTC, hbandura commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +        echo "Sync not completed. Latest block is $((-DIFF)) seconds old"
will -$DIFF show '3' or '--3' ?

2020-09-25 21:19 UTC, hbandura commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +if [ $LATEST -eq $LATEST 2> /dev/null ]; then
it prints 'sh: [: : integer expression expected' if i remove it when LATEST is not a number

2020-09-29 18:04 UTC, jcortejoso approved these changes
lgtm

2020-09-29 18:04 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +if [ $LATEST -eq $LATEST 2> /dev/null ]; then
I think that is bc you need to quotes with `"` the variables, so `[ "$LATEST" -eq "$LATEST" ]`. Another check we could use instead is `[ -z "$LATEST" ]` that checks if $LATEST is defined and not empty string.

2020-09-29 18:04 UTC, jcortejoso commented on helm-charts/sync-test-node/scripts/is_synced.sh
> +        echo "Sync not completed. Latest block is $((-DIFF)) seconds old"
Oh, I was not considering that $DIFF could be negative. Then is perfect as it is.

2020-09-29 18:54 UTC, merged